apiVersion: apps/v1
kind: Deployment
metadata:
  name: carbide-dhcp
  namespace: default
  annotations:
    configmap.reloader.stakater.com/reload: "carbide-dhcp-config"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: carbide-dhcp
  template:
    spec:
      containers:
        - name: carbide-dhcp
          image: yourdockerregistry.com/path/to/carbide-core:latest
          command: ['sh', '-c', 'mkdir -vp /var/run/kea /var/lib/kea && /sbin/kea-dhcp4 -c /tmp/kea_config.json']
          env:
            - name: FORGE_ROOT_CAFILE_PATH
              value: /var/run/secrets/spiffe.io/ca.crt
            - name: FORGE_CLIENT_CERT_PATH
              value: /var/run/secrets/spiffe.io/tls.crt
            - name: FORGE_CLIENT_KEY_PATH
              value: /var/run/secrets/spiffe.io/tls.key
            - name: RUST_BACKTRACE
              value: "full"
            - name: RUST_LIB_BACKTRACE # See https://doc.rust-lang.org/std/backtrace/index.html#environment-variables
              value: "0"
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
          ports:
            - name: udp
              containerPort: 67
            - name: metrics
              containerPort: 1089
          volumeMounts:
            - name: spiffe
              mountPath: /var/run/secrets/spiffe.io
              readOnly: true
            - name: config
              mountPath: /tmp
      volumes:
        - name: spiffe
          secret:
            secretName: carbide-dhcp-certificate
        - name: config
          configMap:
            defaultMode: 420
            name: carbide-dhcp-config
