apiVersion: v1
kind: Service
metadata:
  name: carbide-dhcp-metrics
  namespace: default
  labels:
    app: carbide-dhcp
    app.kubernetes.io/metrics: carbide-dhcp
spec:
  ports:
    - port: 1089
      name: http
      protocol: TCP
      targetPort: 1089
