kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: carbide-dhcp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: carbide-dhcp
subjects:
  - kind: ServiceAccount
    name: carbide-dhcp
    namespace: default
