kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: carbide-dhcp
  namespace: default
rules:
  - apiGroups: ["cert-manager.io"]
    resources: ["certificaterequests"]
    verbs: ["create"]
