[package]
name = "mlxconfig-device"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { features = ["derive"], workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
clap = { features = ["derive"], workspace = true }
tokio = { features = ["full"], workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { features = ["env-filter"], workspace = true }
quick-xml = { features = ["serialize"], workspace = true }
prettytable-rs = { workspace = true }
regex = { workspace = true }
chrono = { features = ["serde"], workspace = true }
hostname = { workspace = true }
mac_address = { features = ["serde"], workspace = true }
rpc = { path = "../../../rpc" }
forge-uuid = { path = "../../uuid" }
prost-types = { workspace = true }

[dev-dependencies]
tokio-test = { workspace = true }
