[package]
name = "carbide-tls"
version = "0.0.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

# TODO: rename to carbide_tls in source
[lib]
name = "forge_tls"

[dependencies]
serde = { features = ["derive"], workspace = true }
serde_json = { workspace = true }
tonic = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
