[package]
name = "carbide-version"
version = "0.0.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
# TODO: rename to carbide_version in source
name = "carbide_version"

[dependencies]
# Nothing should be here. The crate needs to be very lightweight
# since its used as a dependency for everything else.

[lints]
workspace = true
