[package]
name = "carbide-ssh-console-mock-api-server"
version = "0.0.1"
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
# TODO: rename to carbide_ssh_console_mock_api_server in source
name = "ssh_console_mock_api_server"

[dependencies]

# local dependencies
carbide-version = { path = "../version" }
carbide-api-test-helper = { path = "../api-test-helper" }
carbide-rpc = { path = "../rpc" }
carbide-uuid = { path = "../uuid" }

tonic = { features = ["tls-ring"], workspace = true }
tonic-prost = { workspace = true }
tonic-prost-build = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
tokio = { features = ["macros"], workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
eyre = { workspace = true }
rustls = { workspace = true, features = ["ring"] }
rustls-pemfile = { workspace = true }

[build-dependencies]
carbide-version = { path = "../version" }
tonic-prost-build = "0.14"
