[package]
name = "carbide-secrets"
version = "0.0.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

# TODO: rename to carbide_secrets in source
[lib]
name = "forge_secrets"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = { workspace = true }
eyre = { workspace = true }
opentelemetry = { workspace = true }
rand = { workspace = true }
serde = { features = ["derive"], workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
vaultrs = { workspace = true }
mac_address = { features = ["serde"], workspace = true }

# [local-dependencies]
bmc-vendor = { path = "../bmc-vendor" }
carbide-rpc = { path = "../rpc" }
carbide-uuid = { path = "../uuid" }

[lints]
workspace = true
