kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: carbide-dns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: carbide-dns
subjects:
  - kind: ServiceAccount
    name: carbide-dns
    namespace: default
