[package]
name = "xtask"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
toml_edit = { workspace = true }
walkdir = { workspace = true }
eyre = { workspace = true }
clap = { workspace = true }
similar = { workspace = true }
version-compare = { workspace = true }

[lints]
workspace = true
