[package]
name = "tonic-client-wrapper"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[features]
default = ["codegen"]
codegen = [
  "dep:proc-macro2",
  "dep:tonic-prost-build",
  "dep:quote",
  "dep:syn",
  "dep:prettyplease",
  "dep:heck",
  "dep:prost-types",
  "dep:lazy_static",
]

[dependencies]
thiserror = { workspace = true }
tonic = { workspace = true }
async-trait = { workspace = true }
proc-macro2 = { optional = true, workspace = true }
tonic-prost-build = { optional = true, workspace = true }
quote = { optional = true, workspace = true }
syn = { optional = true, workspace = true }
prettyplease = { optional = true, workspace = true }
heck = { optional = true, workspace = true }
prost-types = { optional = true, workspace = true }
lazy_static = { optional = true, workspace = true }

[dev-dependencies]
temp-dir = { workspace = true }

[lints]
workspace = true
