[package]
name = "carbide-ssh-console-fuzz"
version = "0.0.1"
edition.workspace = true
description = "Carbide is a Bare Metal Provisioning system with auto-discovery and API based machine manipulation"
license.workspace = true
authors.workspace = true

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = { workspace = true }
carbide-ssh-console = { path = "../ssh-console" }

[[bin]]
name = "ssh_console_escape_filter"
path = "fuzz_targets/ssh_console_escape_filter.rs"
test = false
doc = false
bench = false
