[package]
name = "carbide-sqlx-testing"
version = "0.0.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
name = "sqlx_testing"

[dependencies]
sqlx = { workspace = true }
sqlx-core = { workspace = true }
tokio = { workspace = true }

# [local-dependencies]
carbide-api-db = { path = "../api-db", default-features = false }

[features]
linux-build = ["carbide-api-db/linux-build"]

[lints]
workspace = true
