[package]
name = "carbide-scout"
version = "0.0.1"
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
name = "scout"

[[bin]]
# TODO: rename to carbide-scout
name = "forge-scout"
path = "src/main.rs"

[dependencies]

# [local-dependencies]
carbide-rpc = { path = "../rpc" }
carbide-host-support = { path = "../host-support" }
carbide-tls = { path = "../tls" }
carbide-uuid = { path = "../uuid" }
carbide-version = { path = "../version" }
carbide-utils = { path = "../utils" }
carbide-machine-validation = { path = "../machine-validation" }
carbide-mlxconfig-device = { path = "../mlxconfig-device" }
carbide-mlxconfig-lockdown = { path = "../mlxconfig-lockdown" }
carbide-mlxconfig-profile = { path = "../mlxconfig-profile" }
carbide-mlxconfig-registry = { path = "../mlxconfig-registry" }
carbide-mlxconfig-runner = { path = "../mlxconfig-runner" }

chrono = { workspace = true }
clap = { workspace = true }
eyre = { workspace = true }
efivar = { workspace = true }
http = { workspace = true }
lazy_static = { workspace = true }
once_cell = { workspace = true }
pwhash = { workspace = true }
regex = { workspace = true }
serde = { features = ["derive"], workspace = true }
serde_json = { workspace = true }
smbios-lib = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true }
tryhard = { workspace = true }
tss-esapi = { workspace = true }
uname = { workspace = true }
uuid = { workspace = true }
reqwest = { default-features = false, features = [
  "rustls-tls",
  "stream",
], workspace = true }
futures-util = { workspace = true }
prost-types = { workspace = true }
x509-parser = { workspace = true }

[build-dependencies]
carbide-version = { path = "../version" }

[lints]
workspace = true
