apiVersion: apps/v1
kind: Deployment
metadata:
  name: carbide-hardware-health
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: carbide-hardware-health
  template:
    metadata:
    spec:
      serviceAccountName: carbide-hardware-health
      containers:
        - name: carbide-hardware-health
          image: yourdockerregistry.com/path/to/carbide-core:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
          command:
            - /bin/sh
            - -c
            - /opt/carbide/forge-hw-health
          env:
            - name: RUST_BACKTRACE
              value: "full"
            - name: RUST_LIB_BACKTRACE # See https://doc.rust-lang.org/std/backtrace/index.html#environment-variables
              value: "0"
          ports:
            - name: metrics
              containerPort: 9009
          livenessProbe:
            failureThreshold: 3
            httpGet:
              port: 9009
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 300
            successThreshold: 1
          resources: {}
          volumeMounts:
            - mountPath: "/var/run/secrets/spiffe.io"
              name: spiffe
              readOnly: true
      volumes:
        - name: spiffe
          secret:
            secretName: carbide-hardware-health-certificate
