kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: carbide-hardware-health
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: carbide-hardware-health
subjects:
  - kind: ServiceAccount
    name: carbide-hardware-health
    namespace: default
