apiVersion: v1
kind: Service
metadata:
  name: carbide-hardware-health
  namespace: default
  labels:
    app: carbide-hardware-health
    app.kubernetes.io/metrics: carbide-hardware-health

spec:
  ports:
    - port: 9009
      name: metrics
      protocol: TCP
