[package]
name = "mqttea-example"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "mqttea-example"
path = "src/main.rs"

[dependencies]
chrono = { features = ["serde"], workspace = true }
clap = { features = ["derive"], workspace = true }
rumqttc = { workspace = true }
serde = { features = ["derive"], workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
prost = { workspace = true }
tokio = { features = ["full"], workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
mqttea = { path = "../mqttea" }

[build-dependencies]
prost-build = "0.14"
