apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/name: carbide-ntp
      app.kubernetes.io/component: ntp
    includeSelectors: true
    includeTemplates: true

resources:
  - statefulset.yaml
  - service.yaml
