apiVersion: v1
kind: Service
metadata:
  name: carbide-unbound
spec:
  selector:
    app.kubernetes.io/instance: carbide-unbound
    app.kubernetes.io/name: unbound
  ports:
    - port: 53
      targetPort: dns-udp
      protocol: UDP
      name: dns-udp
    - port: 53
      targetPort: dns-tcp
      protocol: TCP
      name: dns-tcp
    - port: 9167
      protocol: TCP
      targetPort: metrics
      name: unbound-metrics
