kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: carbide-ssh-console-rs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: carbide-ssh-console-rs
subjects:
  - kind: ServiceAccount
    name: carbide-ssh-console-rs
    namespace: default
