apiVersion: v1
kind: Service
metadata:
  name: carbide-api-profiler
  namespace: default
  labels:
    app: carbide-api
    app.kubernetes.io/metrics: carbide-api
spec:
  ports:
    - port: 1081
      name: http
      protocol: TCP
      targetPort: 1081
