kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: carbide-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: carbide-api
subjects:
  - kind: ServiceAccount
    name: carbide-api
    namespace: default
