apiVersion: v1
kind: Service
metadata:
  name: carbide-pxe-metrics
  namespace: default
  labels:
    app: carbide-pxe
    app.kubernetes.io/metrics: carbide-pxe
spec:
  ports:
    - port: 8080
      name: http
      protocol: TCP
      targetPort: 8080
