kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: carbide-pxe
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: carbide-pxe
subjects:
  - kind: ServiceAccount
    name: carbide-pxe
    namespace: default
