[package]
name = "carbide-network"
version = "0.0.0"
edition.workspace = true
description = "Common networking code for Forge components."
license.workspace = true
authors.workspace = true

# TODO: rename to carbide_network in source
[lib]
name = "forge_network"

[features]
default = ["ipnetwork"]
ipnetwork = ["dep:ipnetwork"]
sqlx = ["dep:sqlx", "dep:ipnetwork"]

[dependencies]
eyre = { workspace = true }
ipnet = { features = ["serde"], workspace = true }
ipnetwork = { workspace = true, features = ["serde"], optional = true }
mac_address = { workspace = true }
serde = { features = ["derive"], workspace = true }
sqlx = { workspace = true, features = [
  "runtime-tokio-rustls",
  "mac_address",
  "ipnetwork",
  "uuid",
  "migrate",
  "postgres",
  "chrono",
  "macros",
  "json",
], optional = true }
thiserror = { workspace = true }

carbide-rpc = { path = "../rpc" }

[lints]
workspace = true
