[package]
name = "prometheus-text-parser"
version = "0.1.0"
description = "Helper to parse prometheus results for testing assertions"
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
thiserror = { workspace = true }

[lints]
workspace = true
